<!DOCTYPE html>
<html lang="en">
{{--FOR DEBUGGING--}}
<?php $user = New \App\User(); $user->name="Vitalii" ?>
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Usably</title>

    {{--FINAL CSS GENERATED BY GULP WITH ELIXIR--}}
    {{--<link href="{{ elixir('css/output/all.css') }}" rel="stylesheet" type="text/css">--}}


    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
    <link href="/css/font-awesome.css" rel="stylesheet" type="text/css">
    <link href="/css/sb-admin.css" rel="stylesheet" type="text/css">
    <link href="/css/plugins/morris.css" rel="stylesheet" type="text/css">
    <link href="/css/style.css" rel="stylesheet" type="text/css">
    <link href="/css/progress-circle.css" rel="stylesheet" type="text/css">

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

    {{-----------------ADDITIONAL LINKS TO FILES GO HERE-----------------------}}
    @yield('header')

</head>

<body>

<div id="wrapper">

    @include('partials.navigation')

    <div class="page-wrapper">
        <div class="container-fluid">

            {{-------------------------------------------CONTENT GOES HERE----------------------------------------------------------}}
            @yield('content')

        </div>
    </div>


</div>


{{--<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>--}}
{{--<script src="http://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.2/js/bootstrap.min.js"></script>--}}


<!-- Morris Charts JavaScript -->
<script src="{{asset('/js/plugins/morris/raphael.min.js')}}"></script>
<script src="{{asset('/js/plugins/morris/morris.min.js')}}"></script>
<script src="{{asset('/js/plugins/morris/morris-data.js')}}"></script>

@yield('footer')


</body>
</html>
